### ISSUE TITLE
Attributes in kebab case instead of camel case

### ISSUE THREAD

**Issue by mnp-mid** [bpmn-miwg/bpmn-in-color#4]
The attributes are with a dash (kebab case) instead of camel case. 
<xs:attribute name="background-color" type="bpmncolor:HexColor"/>
<xs:attribute name="border-color" type="bpmncolor:HexColor"/>
<xs:attribute name="color" type="bpmncolor:HexColor"/>
 
Should it not be backgroundColor or borderColor. 
It seems like its based on CSS definition, however it is than an exception to all other parts in the bpmn file and camel case is actually used as default.

**Comment by dgagne** [comment]
BPMN MIWG 8 Sep 2021 Webmeeting
o	At the time of the creation of BPMN in Color it was decided to align with what was done in CSS as this was not part of the BPMN spec. By now the group does not see any value in doing this alignment.
