### ISSUE TITLE
HexColor defines no transparency

### ISSUE THREAD

**Issue by mid-back** [bpmn-miwg/bpmn-in-color#5]
The color definition lacks transparency.
In [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/color#formal_syntax) the alpha value represents the transparency of a color.
The HexColor does only support red, green and blue value.

I suggest a fourth optional alpha value at the end of the HexColor.
<xs:pattern value="#[0-9a-fA-F]{6}([0-9a-fA-F]{2})?"/>

The effect of transparency applies each time, when containers are used in BPMN, e.g. colored lanes with transparent flow elements.

**Comment by dgagne** [comment]
BPMN MIWG 8 Sep 2021 Webmeeting
o	Given that the Diagram Definition (DD) covers these topics and that a subset of an early version of DD was pasted in BPMN at the time of its release (when DD was not yet an official standard). We felt this would be better addressed with a BPMN 3.0 RFP/submission)
